apiVersion: v1
kind: Plugin
metadata:
  author: RockChinQ
  name: HelloPlugin
  repository: https://github.com/langbot-app/langbot-plugins/tree/main/misc/HelloPlugin
  version: 0.1.4
  description:
    en_US: This plugin is an experimental plugin that provides demos on `EventListener`,
      `Tool` and `Command` components.
    zh_Hans: 这是一个实验性的插件，提供了 `EventListener`、`Tool` 和 `Command` 组件的演示。
    zh_Hant: 這是一個實驗性的插件，提供了 EventListener、Tool 和 Command 元件的演示。
    ja_JP: EventListener、Tool、Commandコンポーネントのデモを提供する実験的なプラグインです。
    vi_VN: Đây là plugin thử nghiệm, cung cấp bản demo cho các thành phần EventListener,
      Tool và Command.
    th_TH: ปลั๊กอินทดลองที่สาธิตการใช้งานส่วนประกอบ EventListener, Tool และ Command
    es_ES: Plugin experimental que proporciona demostraciones de los componentes EventListener,
      Tool y Command.
  label:
    en_US: HelloPlugin
    zh_Hans: HelloPlugin
    zh_Hant: HelloPlugin
    ja_JP: HelloPlugin
    vi_VN: HelloPlugin
    th_TH: HelloPlugin
    es_ES: HelloPlugin
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
    Command:
      fromDirs:
      - path: components/commands/
    Tool:
      fromDirs:
      - path: components/tools/
execution:
  python:
    path: main.py
    attr: HelloPlugin
  sharedRuntime: shared-runtime-v1
  componentModel: stateless-v1
