# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import asyncio
from typing import Any

from langbot_plugin.api.definition.components.tool.tool import Tool

from .mux import process

import logging


class VisitWeb(Tool):

    async def call(self, params: dict[str, Any]) -> dict[str, Any]:
        """Fill your tool code here"""
        try:
            if 'brief_len' not in params:
                params['brief_len'] = 4096

            print(f'start visit web: {params["url"]}')
            # The site adapters fetch with the blocking `requests` library. Run the
            # whole call in a worker thread so the shared event loop keeps serving
            # other tenants while this page is fetched/parsed.
            return await asyncio.to_thread(process, params['url'], params['brief_len'])
        except Exception as e:
            logging.error("[Webwlkr] error visit web: {}".format(e))
            return "error visit web:{}".format(e)