# Auto generated by LangBot Plugin SDK.
# Please refer to https://langbot.app/docs/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin

DEFAULT_LANGUAGE = 'en_US'


class EssentialCommands(BasePlugin):
    """Essential commands plugin.

    One object graph serves every installation of this artifact, so the
    configured language is resolved from the current invocation config on
    every call instead of being captured in ``initialize()`` (shared placement
    initializes plugins with an empty config).
    """

    def get_language(self) -> str:
        """Language configured for the current invocation."""
        return self.get_config().get('language') or DEFAULT_LANGUAGE
