apiVersion: v1
kind: EventListener
metadata:
  name: default
  label:
    en_US: EBA Event Probe Listener
    zh_Hans: EBA 事件探针监听器
spec:
execution:
  python:
    path: default.py
    attr: EBAEventProbeListener
