# Auto generated by LangBot Plugin SDK.
# HumanTakeover EventListener - 记录消息并在接管时阻断 AI。
from __future__ import annotations

import logging

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message

logger = logging.getLogger(__name__)


def _extract_content(message_chain: platform_message.MessageChain) -> tuple[str, str]:
    """从消息链提取展示内容。

    返回 (content_type, content):
    - 优先文本;若仅有图片则返回图片 url/base64。
    """
    text_parts: list[str] = []
    image_ref = ""
    for comp in message_chain:
        if isinstance(comp, platform_message.Plain):
            text_parts.append(comp.text)
        elif isinstance(comp, platform_message.Image):
            image_ref = comp.url or comp.base64 or "[图片]"
        elif isinstance(comp, platform_message.At):
            text_parts.append(f"@{comp.display or comp.target} ")

    text = "".join(text_parts).strip()
    if text:
        return "text", text
    if image_ref:
        return "image", image_ref
    return "text", ""


class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()

        @self.handler(events.PersonMessageReceived)
        async def on_person_message(event_context: context.EventContext):
            await self._handle_received(event_context, "person")

        @self.handler(events.GroupMessageReceived)
        async def on_group_message(event_context: context.EventContext):
            await self._handle_received(event_context, "group")

        @self.handler(events.NormalMessageResponded)
        async def on_ai_responded(event_context: context.EventContext):
            await self._handle_ai_responded(event_context)

    async def _bot_uuid_for(self, event_context: context.EventContext) -> str:
        """Return the trusted bot identity of this event, or "" when unavailable.

        The bot uuid comes from the Host query, not from the serialized event, so it
        cannot be chosen by the payload. It is required: a session keyed without it
        could collide with another bot's conversation.
        """
        try:
            bot_uuid = await event_context.get_bot_uuid()
        except Exception as e:  # noqa: BLE001
            logger.warning("HumanTakeover get_bot_uuid failed: %s", e)
            bot_uuid = ""
        return str(bot_uuid or "")

    async def _handle_received(
        self, event_context: context.EventContext, session_type: str
    ):
        event = event_context.event
        plugin = self.plugin

        # 获取 bot uuid(用于人工回复时主动发送): 会话键必须包含 Bot 身份,
        # 否则同一安装内多个 Bot/适配器的同 ID 会话会互相覆盖历史与回复目标。
        bot_uuid = await self._bot_uuid_for(event_context)
        if not bot_uuid:
            logger.error(
                "HumanTakeover dropped an event without a trusted bot uuid; "
                "refusing to key a session without bot identity"
            )
            return

        session_key = plugin.make_session_key(
            event.launcher_type, event.launcher_id, bot_uuid
        )

        # 收消息时缓存适配器(此时 bot 在线,避免人工发送时反复请求出错)
        adapter = ""
        try:
            bot_info = await plugin.get_bot_info(bot_uuid)
            adapter = bot_info.get("adapter") or ""
        except Exception as e:  # noqa: BLE001
            logger.warning("HumanTakeover get_bot_info for adapter failed: %s", e)

        # 提取发送者信息与会话名称
        sender_id = str(event.sender_id)
        sender_name = sender_id
        session_name = ""
        try:
            msg_event = event.message_event
            sender = getattr(msg_event, "sender", None)
            if session_type == "group":
                if sender is not None:
                    sender_name = getattr(sender, "member_name", "") or sender_id
                    group = getattr(sender, "group", None)
                    if group is not None:
                        session_name = getattr(group, "name", "") or str(
                            event.launcher_id
                        )
            else:
                if sender is not None:
                    sender_name = (
                        getattr(sender, "nickname", "")
                        or getattr(sender, "remark", "")
                        or sender_id
                    )
                    session_name = sender_name
        except Exception as e:  # noqa: BLE001
            logger.warning("HumanTakeover extract sender failed: %s", e)

        content_type, content = _extract_content(event.message_chain)

        await plugin.record_message(
            session_key=session_key,
            session_type=session_type,
            target_id=str(event.launcher_id),
            bot_uuid=bot_uuid,
            session_name=session_name,
            role="user",
            sender_id=sender_id,
            sender_name=sender_name,
            content_type=content_type,
            content=content,
            adapter=adapter,
        )

        # 触发词匹配:命中则标记未处理(红点),并按配置自动接管
        if content_type == "text" and content:
            word = plugin.match_trigger(content)
            if word:
                await plugin.mark_unread(session_key, word)
                if plugin.get_auto_takeover_on_trigger():
                    await plugin.set_takeover(session_key, True)
                    logger.info(
                        "HumanTakeover auto took over session %s by trigger '%s'",
                        session_key,
                        word,
                    )

        # 接管中:阻断 AI 处理
        if plugin.is_taken_over(session_key):
            event_context.prevent_default()
            event_context.prevent_postorder()
            logger.info(
                "HumanTakeover blocked AI for session %s (taken over)", session_key
            )

    async def _handle_ai_responded(self, event_context: context.EventContext):
        """记录 AI 的回复内容,便于在面板中查看完整对话。"""
        event = event_context.event
        plugin = self.plugin

        # 与收消息一致: 会话键必须携带可信 Bot 身份,否则会写入另一个 Bot 的历史。
        bot_uuid = await self._bot_uuid_for(event_context)
        if not bot_uuid:
            logger.error(
                "HumanTakeover dropped an AI response without a trusted bot uuid; "
                "refusing to key a session without bot identity"
            )
            return

        session_key = plugin.make_session_key(
            event.launcher_type, event.launcher_id, bot_uuid
        )

        # 若该会话已接管,理论上不会触发 AI 回复;保险起见再次校验
        if plugin.is_taken_over(session_key):
            return

        response_text = getattr(event, "response_text", "") or ""
        if not response_text:
            return

        sess = plugin.sessions.get(session_key)
        session_type = sess.get("type") if sess else event.launcher_type
        session_name = sess.get("name", "") if sess else ""

        await plugin.record_message(
            session_key=session_key,
            session_type=session_type or "person",
            target_id=str(event.launcher_id),
            bot_uuid=bot_uuid,
            session_name=session_name,
            role="ai",
            sender_id="",
            sender_name="AI",
            content_type="text",
            content=response_text,
        )
