apiVersion: v1
kind: Command
metadata:
  name: memory
  label:
    en_US: Memory
    zh_Hans: 记忆
  description:
    en_US: Manage long-term memory
    zh_Hans: 管理长期记忆
spec:
execution:
  python:
    path: memory.py
    attr: Memory
